### ISSUE TITLE
Error handling for custom modules in web UI

### ISSUE THREAD

**Issue by hoodmane** [SpectralSequences/sseq#126]
JD tried to upload a Bruner module definition format file and complained that we provided no error message. Ideally it would be nice if we caught the invalid JSON error and indicated in some way that the module file is incorrect.

**Comment by JoeyBF** [comment]
What would be the steps to reproduce? I forget where we upload these

**Comment by hoodmane** [comment]
Sorry, should have given more details!

1. Go to https://spectralsequences.github.io/sseq/
2. Hit "upload" button
3. Add a file that does not contain valid JSON

**Comment by JoeyBF** [comment]
Got it, I'll check it out. Thanks!

**Comment by hoodmane** [comment]
I suspect that there are similar problems if the file has valid json but is in some way an invalid module definition...

**Comment by hoodmane** [comment]
Thanks @JoeyBF!
