### ISSUE TITLE
Tidy up unstable algebra interface

### ISSUE THREAD

**Issue by dalcde** [SpectralSequences/sseq#24]
I believe at the moment we are mixing two different strategies when it comes to unstable algebras. There are two ways we might want to deal with this:

1. Every algebra is potentially unstable
2. Every algebra is by default stable; A separate interface is made for unstable algebras

The advantage of the first option is that we can reuse the same structs (e.g. free modules) for both stable and unstable modules. From a user's point of view, this is only pertinent to free and finitely presented modules, since being an unstable module is a property, not a structure. For other modules (e.g. finite dimensional modules), knowing that it is unstable allows us to save some space and what not.

The advantage of the second option is that it simplifies the stable use case, which is what is pertinent in most cases. Currently a lot of code just throws random values into the excess parameter.

It is possible to use associated constants to get some middle ground. One option is to let AdemAlgebra have a const parameter for toggling stability.

@hoodmane It appears you have some WIP in this direction (e.g. I don't think basis_filter is actually used anywhere). Can you clarify the status of this work in case I want to do some significant refactoring?

**Comment by hoodmane** [comment]
The idea of the `basis_filter` was to provide a quick way to quotient by a subspace generated by basis elements. Of course it leaves empty unused slots in all the vectors, but I think I decided that for the time being it was quicker not to do the rearrangement. 

I think the `basis_filter` actually predates the current system, I stopped using it when I realized that there was an extremely dramatic speedup by sorting low excess basis elements first and quitting as soon as you hit the first too-high-excess element. I believe that I copied this stuff fairly directly from the C version so git blame might not be as useful as you'd hope.

**Comment by dalcde** [comment]
Is it okay for me to remove basis_filter then?

**Comment by hoodmane** [comment]
Yeah sounds fine since it isn't used.

**Comment by dalcde** [comment]
I'm now having a look at this again. I think my current thought is to adopt the following strategy:

Introduce a new trait `UnstableAlgebra` that has `dimension_unstable` and `multiply_unstable` functions, and change the `Algebra` trait methods to no longer take in an `excess` argument, which is what we want most of the time. To handle the split between stable and unstable free modules, we can use const generics with a boolean parameter to minimize the code duplication.

@hoodmane what do you think? (also, can you clarify why `adem_basis_element_length_sort_order` in `adem_algebra.rs` is for?)
