### ISSUE TITLE
Revisit the saving mechanism

### ISSUE THREAD

**Issue by JoeyBF** [SpectralSequences/sseq#44]
As we push into higher stems, I think it might be useful to rethink the way we store resolutions. Right now the `Resolution` struct is written to a file as-is. While that has its advantages, I can think of a few downsides.

- Very sensitive to the data layout. Any minor change is susceptible to make all prior archives unreadable, unless we're careful.
- Impossible to inspect manually.
- No support for incremental saving. This is the big one. When we start testing multi-day/week runs it will be inevitable that some crashes will happen, and it would be great to not lose the quasi-inverses that we will have spent many CPU-hours calculating. I think it would help to fragment the archive into smaller files. Maybe quasi-inverses could be stored in their own files?
- No compression. As the matrices get bigger the storage space becomes an issue. I've calculated that computing into the 200+ stems will require on the order of 10TB of disk space at the very least. It would be helpful to have the ability of writing/reading compressed data, especially since the archives are empirically very compressible. (I just checked and the resolution of S_2 up to t = 100 can be compressed by 60% using gzip.)

I don't have a concrete suggestion for a replacement right now, but I think it's something we should consider before pushing computations further (see #30).

**Comment by JoeyBF** [comment]
I think the IO costs are going to be minimal compared to the rest of the computation, and there's also always the option of dispatching the save to a dedicated thread.

I think sqlite might still be too cumbersome.  I spoke with a friend today and he said that geneticists, who use more than 1 PB of storage on the WSU grid, have tools that exclusively read in / write out `.tar.gz` tarballs. That might be worth considering. It would really prefer having dedicated files for the quasi-inverses, so that we can mmap them and use them as-is without deserializing first. In large stems a single quasi-inverse can occupy _several_ GB.

I hadn't thought about storing the quasi-inverses only on the generators. That would certainly cut down the storage requirements by a lot, but at the cost of making it harder to compute lifts down the line. I would say that more experimentation is needed.

**Comment by dalcde** [comment]
This is my plan of attack:

The resolution is stored in a directory, which we shall call `/` for the purposes of this discussion. This has three subdirectories: `/differentials/`, `/quasi-inverses/` and `/kernels/`. In each directory, the data of each bidegree is stored in a file called `s_t.ext` for some extension to be determined, and each file is compressed.

For the kernels directory, we delete the file once we no longer need it.

This allows us to save data incrementally, and also it is now possible to load a smaller resolution given a save data.

Saving the quasi-inverses separately from the differentials makes it easy to implement #29.

Each save file will be compressed. I've experimented with several compression algorithms, trying to compress the data for `s = 3 to 7` and `t = 140` with the Milnor basis. The results are as follows (the numbers following an algorithm represent the compression level):
```
algorithm: write_time read_time total size
raw: 292.87629ms 245.78584ms 795806013
snap: 697.168531ms 854.239285ms 415882110
zstd 1: 2.275886699s 1.026356308s 365239503
zstd 3: 4.799971583s 881.428894ms 359660237
zstd 21: 168.854727843s 1.253918986s 339565081
gzip 1: 5.901635364s 2.558595974s 387680655
gzip 9: 137.415523131s 2.902248096s 378109490
brotli 1: 4.165027028s 4.57096398s 368688292
brotli 8: 48.285620746s 7.624755351s 353941345
```

From this data I think zstd is a clear winner. Only snap is faster but we get a ~20% size improvement. During write time, we can use compression level 1, and then after computations are done we can re-compress the data to a higher compression level to save space. My main concern with zstd is that it uses C++ bindings so it cannot be used with wasm.

An alternative approach is to always write the data uncompressed but be able to read both uncompressed and compressed data. We can then compress separately when we are idle.

I'll probably start working on this tomorrow. Comments are welcome.

NB. Compressing each bidegree individually is necessarily less efficient for compression purposes, but the ability to work incrementally is too useful to forgo imo.

**Comment by JoeyBF** [comment]
I agree with mostly everything. Right now the main bottleneck is the space usage, both in storage and in RAM, so it makes sense to sacrifice some loading time. It's also a good idea to be more modular so that we avoid problems when changing the saving scheme for a given struct.

However I think it is essential to be able to work with uncompressed as well as compressed data. In the near future it will be possible to load vectors and matrices directly from disk using `mmap` and zero-copy deserialization, so it is crucial that the data be stored uncompressed in that case.

For the compression algorithm, have you tried lz4 using something like [lz4_flex](https://crates.io/crates/lz4_flex)? They claim to be the fastest compression scheme in pure Rust.

**Comment by dalcde** [comment]
lz4 data is as follows:
```
lz4: 1.277215386s 417.09343ms 398264945
```

This gives slightly smaller sizes than snap and significantly faster decompression, but compression is slower. I think compression/decompression speed are less important, and compression time is specially unimportant. So it may make sense to use this over snap.

mmap is very tricky to do safely, since users would be able to modify the underlying files while the program is running, which gives instant UB. If we are happy to ignore this possibility then this should be easy to implement with uncompressed data.

It should not be too difficult to support multiple data formats.

Are there particular computations you want to do where storing even a single quasi-inverse in memory is problematic? In these cases we might even be able to get away with reading the quasi-inverse line by line. We can save the quasi-inverse in the format

```
<1st basis vector of image>
<lift of 1st basis vector>
<2nd basis vector of image>
<lift of 2nd basis vector>
...
```
and compute the quasi-inverse on a set of vector in a single pass through the file. Then at any point in time we only have to deal with two rows (plus whatever we are working with).

This seems to be a pretty niche use case, though; we need to have had enough memory to generate the quasi-inverse in the first place, so this is most likely only relevant if we want to use the pre-computed values on a different machine that is significantly less powerful.

**Comment by JoeyBF** [comment]
> Are there particular computations you want to do where storing even a single quasi-inverse in memory is problematic?

Not right now, but if we minimize the memory usage we'll be able to spread the work over several machines in a cluster. I'm imagining that should be feasible in the not-too-distant future.

I think that storing the quasi-inverses in a zero-copy-deserializable format will make it much easier to compute extra data in the future. Once we have a large resolution, we will want to use the quasi-inverses to compute the products and Massey products in Ext, and the d2 differentials in the E_2 page. If we implement efficient matrix-matrix multiplication that should not take too much time, but that's only if they are accessible as matrices. I feel like that's the point of saving the quasi-inverses anyway, to make generating lifts easier in the next step.
