### ISSUE TITLE
Hairy Pyodide build processes for repl webclient

### ISSUE THREAD

**Issue by hoodmane** [SpectralSequences/sseq#5]
There are a few steps in the build for the repl webclient that are a bit weird:

### 1. Pyodide setup. 

In order to build pyodide, I had to build CPython 3.8 from source. At the time I did this, the Pyodide repl was still based on Python 3.7, but in Python 3.7 the `PyCF_ALLOW_TOP_LEVEL_AWAIT` flag is not available, so I had to convince it to use Python 3.8 instead. They were already planning to move to Python 3.8 so this wasn't too hard. I also had to install `zlib1g-dev` and `libffi-dev` in addition to the dependencies they had listed on the website. I also modified the Makefile and the folder "packages" to remove dependencies like LAPACK and NumPy which I don't need, to update the versions of Parso and Jedi, and to introduce my python packages (detailed in part 2).

Now they have a docker image with a prebuilt copy of Python 3.8. I don't know how docker works -- maybe it would be reasonably easy for me to make my own docker image with my modifications to packages and Makefile and then it would be easy for others to build from there?

Another anomaly worth mentioning is that you must remove `build/pyodide*` before running make again or the files pyodide* get corrupted.

### 2. Updating the custom Python packages

There are two custom python packages `crappy_python_multitasking` and `spectralsequence_chart`. As far as I could figure out, it doesn't seem possible to convince Pyodide to do an install of a local package, it wants to download the packages from pip. Thus, every time I want to update these dependencies I need to push a new copy to pypi. 
`crappy_python_multitasking` is a C extension to make my interrupt system work and in order to upload it to pypi it has to be compiled on a "many-linux" system for compliance with CPython's ABI rules. CPython provides a a docker image for this purpose for convenience, but I remember it took a bit of effort.
Probably `crappy_python_multitasking` won't ever change (after the python module, docstrings, etc set up it's only about 60 lines of code), but I have been changing `spectralsequence_chart` frequently.

Once the new dependencies are updated on pypi, then it suffices to run 
```sh
   pyodide/bin/pyodide mkpkg <package_name>
   pyodide/bin/pyodide buildpkg --package_abi 1 packages/<package_name>/meta.yml
   cp packages/<package_name>/build/<package_name>.* build
```

### 3. The nginx server

This isn't exactly a build process, but maybe I should somehow document the nginx server configuration I'm using. There's nothing complicated there, just some symlinks, it needs to have the Mimetype for wasm added it, and there's the https setup.

**Comment by dalcde** [comment]
On Thu, Nov 26, 2020 at 11:04:10AM -0800, Hood Chatham wrote:
>There are a few steps in the build for the repl webclient that are a bit weird:
>
>1. Pyodide setup. In order to build pyodide, I had to build CPython 3.8 from source. At the time I did this, the Pyodide repl was still based on Python 3.7, but in Python 3.7 the `PyCF_ALLOW_TOP_LEVEL_AWAIT` flag is not available, so I had to convince it to use Python 3.8 instead. They were already planning to move to Python 3.8 so this wasn't too hard. I also had to install `zlib1g-dev` and `libffi-dev` in addition to the dependencies they had listed on the website. I also modified the Makefile and the folder "packages" to remove dependencies like LAPACK and NumPy which I don't need, to update the versions of Parso and Jedi, and to introduce my python packages (detailed in part 2).

I assume at this point we are just waiting for the next pyodide release
and then this becomes a non-problem.

>2. Updating the dependencies `crappy_python_multitasking` and `spectralsequence_chart`. As far as I could figure out, it doesn't seem possible to convince Pyodide to do an install of a local package, it wants to download the packages from pip. Thus, every time I want to update these dependencies I need to push a new copy to pypi.
>`crappy_python_multitasking` is a C extension to make my interrupt system work and in order to upload it to pypi it has to be compiled on a "many-linux" system for compliance with CPython's ABI rules. CPython provides a a docker image for this purpose for convenience, but I remember it took a bit of effort.
>Probably `crappy_python_multitasking` won't ever change (after the python module, docstrings, etc set up it's only about 60 lines of code), but I have been changing `spectralsequence_chart` frequently.

I haven't read carefully but this seems to disagree:
https://pyodide.readthedocs.io/en/latest/new_packages.html

>3. This isn't exactly a build process, but maybe I should somehow document the nginx server configuration I'm using. There's nothing complicated there, just some symlinks, it needs to have the Mimetype for wasm added it, and there's the https setup.

What I would really prefer is to have *no* build artifacts committed,
and have CI build everything from scratch everytime. CI can then send
the built files somewhere, e.g. GH pages.

This ensures there is a working and somewhat-documented build process at
every point in time. Currently it is possible that some parts of the
build process in fact don't work, but we don't notice because the build
artifacts we need already exist.

**Comment by dalcde** [comment]
Specifically, to build pyodide packages, instead of using the `mkpkg` script, you can write a `meta.yaml` file by hand, and then run the `buildpkg` script. I believe the following `meta.yaml` inside `sseq/chart/python/` should work:
```
package:
    name: spectralsequence_chart
    version: 0.0.18
source:
    path: ./spectralsequence_chart/
```

**Comment by hoodmane** [comment]
Great. When I first started using pyodide, I'm pretty sure that https://pyodide.readthedocs.io/en/latest/new_packages.html only had a very brief stub -- in particular, there was no explanation of what the `meta.yaml` fields mean. I'm glad to see the docs have improved, now I can stop spamming pip with quite so many minor version changes.

**Comment by hoodmane** [comment]
> What I would really prefer is to have *no* build artifacts committed,
> and have CI build everything from scratch everytime. CI can then send
> the built files somewhere, e.g. GH pages.
> 
> This ensures there is a working and somewhat-documented build process at
> every point in time. Currently it is possible that some parts of the
> build process in fact don't work, but we don't notice because the build
> artifacts we need already exist.

Yes that is obviously preferable, and I'm really glad you're going through and checking whether things build correctly. The way it is now, I certainly worry about the build process not working, but I don't have quite have the energy or inclination to figure out how to get CI set up left to my own accord.

**Comment by dalcde** [comment]
I think the best way to do CI is to have a build script, and the CI part just executes the script and checks it does not error. I think we should go for GitHub actions

**Comment by dalcde** [comment]
For packaging pure python packages, I have now learnt that the simplest way is to build a wheel and load it via micropip, which can take an arbitrary url. We still need to deal with pyodide sources if we have a C-based library, though. They use a custom version of emscripten that is not ABI compatible with upstream emscripten.

In other news, pyodide distributes compiled versions of latest github master at `https://cdn.jsdelivr.net/pyodide/v0.15.0/full/pyodide.js` so we can use that if the changes we seek are all upstreamed, avoiding the need to compile pyodide in any way.

**Comment by dalcde** [comment]
Now that upstream includes a better-named version of `crappy-python-multitasking`, we can now use upstream master. I think we can/should close this once we actually do so.

**Comment by hoodmane** [comment]
>> I have now learnt that the simplest way is to build a wheel and load it via micropip, which can take an arbitrary url

We'd better fix micropip before we do this. I'll open an issue about it on Pyodide.

**Comment by dalcde** [comment]
What's the issue with micropip? It seems to be working fine now.  (cf. e0f9498)

**Comment by hoodmane** [comment]
I opened an issue: iodide-project/pyodide#867
