### ISSUE TITLE
Idea: FpVectorP<2> with concurrent write access

### ISSUE THREAD

**Issue by dalcde** [SpectralSequences/sseq#55]
Since addition mod 2 is xor, we can have multpile threads writing to the same `FpVectorP<2>` using `AtomicU64::fetch_xor`. This can be useful for parallelizing certain operations, such as acting on a `FreeModule`.

This will make the mod 2 situation substantially different from the odd prime situation though. Maybe wait till specialization...

**Comment by JoeyBF** [comment]
Are you suggesting we use `AtomicU64`s as limbs instead of `u64`s? We could always have something like `AtomicFpVector` and have it implement `BaseVector`, assuming #53.

**Comment by dalcde** [comment]
The transmute fn(&mut [u64]) -> &mut [AtomicU64] is safe, but other functions will need Atomic support. I don't have concrete architectural ideas at the moment

**Comment by dalcde** [comment]
I've done a bit of experiment and I think this is just a bad idea. Concurrent atomic writes still incur some synchronization cost, and just makes everything really slow.
