### ISSUE TITLE
Implement signal handling

### ISSUE THREAD

**Issue by JoeyBF** [SpectralSequences/sseq#79]
I think it would be a good idea to add some handlers to make sure we don't leave a save directory in a dirty state. I'm thinking of intercepting:

 - SIGINT/SIGTERM to remove any malformed files before exiting.
 - SIGUSR1 to dump a summary of ongoing computations to stderr (if `logging` is enabled).

Maybe we could also intercept SIGSTP to print the same data as SIGUSR1.

**Comment by dalcde** [comment]
Sounds like a good idea to me. Might be tricky to do safely though.

> - SIGUSR1 to dump a summary of ongoing computations to stderr (if `logging` is enabled).

For a long time, each filtration had its own thread and the thread was
named after the filtration, so you can check what it is doing with top.
We now use rayon so it's gone.
