### ISSUE TITLE
Flaky chart test

### ISSUE THREAD

**Issue by dalcde** [SpectralSequences/sseq#86]
e.g. https://github.com/SpectralSequences/sseq/runs/5711814604 and https://github.com/SpectralSequences/sseq/runs/5703909304 .

**Comment by dalcde** [comment]
If you don't have time to look at this, is there a way to temporarily disable the test?

**Comment by hoodmane** [comment]
Resolved by 4fee0d11c712834d25d721b7306271685c1e859c.
