### ISSUE TITLE
Another failed chart test

### ISSUE THREAD

**Issue by dalcde** [SpectralSequences/sseq#91]
https://github.com/SpectralSequences/sseq/runs/5964435372

**Comment by hoodmane** [comment]
Huh that looks like the same one. I would have sworn I fixed it.

**Comment by hoodmane** [comment]
Oh it's with a differential instead of an extension or something like that.

**Comment by hoodmane** [comment]
There's probably a few more of these but I fixed this particular failure in b0d8814548dfc8909b970aa7c2b49a9fd9a427a2.
